package com.yoda.codingagent.core.api;

public enum ErrorCode {
    INVALID_REQUEST,
    UNKNOWN_WORKSPACE,
    WORKSPACE_IN_USE,
    SESSION_BUSY,
    MODEL_AUTHENTICATION,
    MODEL_RATE_LIMIT,
    MODEL_TIMEOUT,
    MODEL_UNAVAILABLE,
    MODEL_STREAM_INTERRUPTED,
    MODEL_PROTOCOL_ERROR,
    UNKNOWN_TOOL,
    INVALID_TOOL_ARGUMENTS,
    PATH_OUTSIDE_WORKSPACE,
    FILE_IO_ERROR,
    COMMAND_DENIED,
    COMMAND_TIMEOUT,
    CONTEXT_LIMIT,
    TURN_LIMIT,
    CANCELLED,
    STORAGE_ERROR,
    INTERNAL_ERROR
}
